---
- name: Install some useful packages
  ansible.builtin.apt:
    install_recommends: no
    update_cache: yes
    cache_valid_time: 3600
    pkg:
      - apt-listchanges
      - apt-transport-https
      - binutils
      - btop
      - byobu
      - bzip2
      - coreutils
      - curl
      - diffutils
      - discover
      - dnsutils
      - ecryptfs-utils
      - file
      - findutils
      - git
      - hostname
      - htop
      - less
      - lsof
      - make
      - moreutils
      - mosh
      - mtr-tiny
      - nano
      - net-tools
      - netcat-openbsd
      - openssh-client
      - openssh-server
      - patch
      - pigz
      - procps
      - psmisc
      - pv
      - rename
      - rsync
      - ruby
      - sharutils
      - socat
      - ssh
      - strace
      - sudo
      - sysstat
      - tcpdump
      - telnet
      - time
      - traceroute
      - unzip
      - usbutils
      - uuid
      - vim
      - wget
      - whois
      - xz-utils
      - zip
      - zsh-syntax-highlighting
      - zstd
