$ANSIBLE_VAULT;1.2;AES256;latham
35323136346233616465383238346366613365663464613731363161353334656239393863363235
3065316638353632643338353534316130653433306233630a383761373735656466343861613963
32303564356261396233386133306238373935313063326530636530343832396666316234353635
6539393663623333340a373931366131636130666165616639376335613534316632633039366661
61356536306563383338656537636564343362333038613466313735636230396331303962616435
34326636646661353637353536333435303861353838656533343661343535336562303637353363
39616166316364383133653435363139373930336364653637316562366532336264396363643761
61333231336330376435346164333765333461666566386633333634613734376565356264323965
65356136373363633633343738336665323531646137326261333066656262623536386233386331
34393330333236376339353931656134666133626136316231666138333231663462383731343262
66373033313435663533386533386662396164646333343666313836316363313862306637333737
61386661396431636563336537303438646465653730376163386565326363653462343238643465
38323937623838343135303166646466626436346439666434343462663131663564363261653835
3038653037323663326436383635313539666132343730343333
